language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rabihmaj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rabihmaj/react-test npm run test

after_success:
  - docker build -t rabihmaj/multi-client ./client
  - docker build -t rabihmaj/multi-nginx ./nginx
  - docker build -t rabihmaj/multi-server ./server
  - docker build -t rabihmaj/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take image and push to docker hub
  - docker push rabihmaj/multi-client
  - docker push rabihmaj/multi-nginx
  - docker push rabihmaj/multi-server
  - docker push rabihmaj/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-west-2-578544437536
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
